### ISSUE TITLE
Error executing script script.simulations_automations_away_presence_night_lights. Invalid data for call_service at pos 2: not a valid value for dictionary value @ data['entity_id']

### ISSUE THREAD

**Issue by Novocaine85** [indomus/simulazione-presenza-con-HA#1]
Ciao,

stavo tentando di integrare questo script seguendo la guida nel vostro sito.

ho modificato simulazione_presenza.yaml in base alle luci che ho a disposizione ripetendo la porzione di script per ogni luce e modificando entity_id per ogni luce:
```yaml
  simulations_automations_away_presence_randomize_lights:
    sequence:
    - service: script.turn_on
      entity_id: script.simulations_automations_away_presence_randomize_times
    - delay: '{{ states("sensor.tempo_casuale_2_fuori_casa") | int }}'
    - service: script.turn_on
      entity_id: script.simulations_automations_away_presence_randomize_states
    - service_template: >-
        {% if is_state("binary_sensor.stato_casuale_1_fuori_casa", "on") %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.cameretta
    - service: script.turn_on
      entity_id: script.simulations_automations_away_presence_randomize_times
    - delay: '{{ states("sensor.tempo_casuale_2_fuori_casa") | int }}'
    - service: script.turn_on
      entity_id: script.simulations_automations_away_presence_randomize_states
    - service_template: >-
        {% if is_state("binary_sensor.stato_casuale_1_fuori_casa", "on") %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.soggiorno1
```

Quando però vado a richiamare uno degli script per verificarne il corretto funzionamento, i log danno questo errore:
```
Error executing script script.simulations_automations_away_presence_night_lights. Invalid data for call_service at pos 2: not a valid value for dictionary value @ data['entity_id']
```

questo lo fa anche negli altri 2 script adibiti (simulations_automations_away_presence_day_lights e simulations_automations_away_presence_evening_lights)

ho provato a lasciare attiva la simulazione senza toccare nulla, ma da comunque l'errore.

ho provato a spulciare un po lo script ma non riesco a trovare il problema.

Grazie per l'eventuale aiuto.
